site_name: Cadwork Python Documentation
site_url: https://python.cadwork.dev/
theme:
    name: material
    nav_style: dark
    logo: cwapi3d_logo_small.png
    version: v28
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 
    features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.instant
nav:
    - Python Guide:
      - Python cadwork: index.md
      - examples: example.md
    - Legacy Documentation:
      - attribute_controller: attribute_controller.md
      - bim_controller: bim_controller.md
      - connector_axis_controller: connector_axis_controller.md
      - element_controller: element_controller.md
      - endtype_controller: endtype_controller.md
      - file_controller: file_controller.md
      - geometry_controller: geometry_controller.md
      - list_controller: list_controller.md
      - machine_controller: machine_controller.md
      - material_controller: material_controller.md
      - menu_controller: menu_controller.md
      - roof_controller: roof_controller.md
      - scene_controller: scene_controller.md
      - shop_drawing_controller: shop_drawing_controller.md
      - utility_controller: utility_controller.md
      - visualization_controller: visualization_controller.md
    - About:
      - About Guide: about.md
markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      separator: '[\s\-\.\_]+'     
  #git-revision-date-localized:
      #type: datetime
  #- mkdocs-versioning:
      #version: 0.3.0                 
extra:
  generator: false
  copyright: Copyright &copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d
      name: CWAPI3D
  #version:
    #provider: mike
      