site_name: Cadwork Python Documentation
site_url: https://python.cadwork.dev/
theme:
    name: material
    nav_style: dark
    logo: cwapi3d_logo_small.png
    version: v28
nav:
    - Legacy Documentation:
      - attribute_controller: attribute_controller.md
      - bim_controller: bim_controller.md
      - connector_axis_controller: connector_axis_controller.md
      - element_controller: element_controller.md
      - endtype_controller: endtype_controller.md
      - file_controller: file_controller.md
      - geometry_controller: geometry_controller.md
      - list_controller: list_controller.md
      - machine_controller: machine_controller.md
      - material_controller: material_controller.md
      - menu_controller: menu_controller.md
      - roof_controller: roof_controller.md
      - scene_controller: scene_controller.md
      - shop_drawing_controller: shop_drawing_controller.md
      - utility_controller: utility_controller.md
      - visualization_controller: visualization_controller.md
    - Python Guide:
      - Python cadwork: index.md
      - examples: example.md
    - About:
      - About Guide: about.md
markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


 
