
# Repository
repo_name: cwapi3d/cwapi3dpython
repo_url: https://github.com/cwapi3d/cwapi3dpython
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 cadwork 

site_name: Cadwork Python Documentation
site_url: https://python.cadwork.dev/
theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg  # cwapi3d_logo2.svg # cwapi3d_logo_small.png #cwapi3d_logo.svg 
    version: v28
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          name: Switch to light mode
          icon: material/weather-sunny
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: grey
        accent: blue
        toggle:
          name: Switch to dark mode
          icon: material/weather-night 
    features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.instant
nav:
    - Python Guide:
      - Python cadwork: index.md
    - Documentation:
      - attribute_controller: attribute_controller.md
      - bim_controller: bim_controller.md
      - connector_axis_controller: connector_axis_controller.md
      - element_controller: element_controller.md
      - endtype_controller: endtype_controller.md
      - file_controller: file_controller.md
      - geometry_controller: geometry_controller.md
      - list_controller: list_controller.md
      - machine_controller: machine_controller.md
      - material_controller: material_controller.md
      - menu_controller: menu_controller.md
      - roof_controller: roof_controller.md
      - scene_controller: scene_controller.md
      - shop_drawing_controller: shop_drawing_controller.md
      - utility_controller: utility_controller.md
      - visualization_controller: visualization_controller.md
    - Examples:
      - geometry examples: geometry.md
      - general examples: example.md
    - About:
      - About Guide: about.md
markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cwapi3d
      repo: cwapi3dpython
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      separator: '[\s\-\.\_]+'     
  #git-revision-date-localized:
      #type: datetime
  #- mkdocs-versioning:
      #version: 0.3.0                 
extra:
  generator: false
  copyright: Copyright &copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d
      name: CWAPI3D
  #version:
    #provider: mike
      