
# Repository
repo_name: cwapi3d/cwapi3dpython
repo_url: https://github.com/cwapi3d/cwapi3dpython
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 cadwork 

site_name: Cadwork Python Documentation
site_url: https://python.cadwork.dev/
theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg  # cwapi3d_logo2.svg # cwapi3d_logo_small.png #cwapi3d_logo.svg 
    version: v28
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          name: Switch to light mode
          icon: material/weather-sunny
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: grey
        accent: blue
        toggle:
          name: Switch to dark mode
          icon: material/weather-night 
    features:
    - search.suggest
    - search.highlight
    # - navigation.tabs
    - navigation.instant
nav:
  - Python API: 
    - Cadwork API: index.md
    - Get Started: get_started.md
    - Debugging: debug.md
  - Documentation:
    - attribute_controller: documentation/attribute_controller.md
    - bim_controller: documentation/bim_controller.md
    - connector_axis_controller: documentation/connector_axis_controller.md
    - element_controller: documentation/element_controller.md
    - endtype_controller: documentation/endtype_controller.md
    - file_controller: documentation/file_controller.md
    - geometry_controller: documentation/geometry_controller.md
    - list_controller: documentation/list_controller.md
    - machine_controller: documentation/machine_controller.md
    - material_controller: documentation/material_controller.md
    - menu_controller: documentation/menu_controller.md
    - roof_controller: documentation/roof_controller.md
    - scene_controller: documentation/scene_controller.md
    - shop_drawing_controller: documentation/shop_drawing_controller.md
    - utility_controller: documentation/utility_controller.md
    - visualization_controller: documentation/visualization_controller.md
  - Examples:
    - geometry examples: examples/geometry.md
    - controller examples: 
      - attribute_controller: examples/attribute_example.md
      - bim_controller: examples/bim_example.md
      - cadwork: examples/cadwork.md
      - connector_axis_controller: examples/connector_example.md
      - element_controller: examples/element_example.md
      - endtype_controller: examples/endtype_example.md
      - file_controller: examples/file_example.md
      - geometry_controller: examples/geometry_example.md
      - list_controller: examples/list_example.md
      - machine_controller: examples/machine_example.md
      - material_controller: examples/material_example.md
      - menu_controller: examples/menu_example.md
      - roof_controller: examples/roof_example.md
      - scene_controller: examples/scene_example.md
      - shop_drawing_controller: examples/shop_drawing_example.md
      - utility_controller: examples/utility_example.md
      - visualization_controller: examples/visualization_example.md
    - slab-frame: examples/frame.md
    - tkinter-gui: examples/tk_gui.md
  - Videos: videos.md
  - About:
    - About Guide: about.md
markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cwapi3d
      repo: cwapi3dpython
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      separator: '[\s\-\.\_]+'     
             
extra:
  generator: false
  copyright: Copyright &copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d
      name: CWAPI3D

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
      