name: Deploy Docs

on: push

jobs:
  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python -m pip install --upgrade pip
      - run: pip install pip-tools
      - run: pip-sync
      - run: python -m mkdocs build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      - uses: actions/deploy-pages@v4
