name: Publish CwAPI3D Package

on:
  push:
    branches:
      - 'main'

jobs:
  publish-to-pypi:
    name: Build and Publish
    runs-on: 'ubuntu-latest'
    environment:
          name: pypi
          url: https://pypi.org/p/cwapi3d
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
