name: Publish CwAPI3D Package

on:
  push:
    branches:
      - 'main'
      
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: 'ubuntu-22.04'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: mv src/attribute_controller/__init__.py src/attribute_controller/__init__.pyi
      - run: mv src/bim_controller/__init__.py src/bim_controller/__init__.pyi
      - run: mv src/cadwork/__init__.py src/cadwork/__init__.pyi
      - run: mv src/connector_axis_controller/__init__.py src/connector_axis_controller/__init__.pyi
      - run: mv src/element_controller/__init__.py src/element_controller/__init__.pyi
      - run: mv src/endtype_controller/__init__.py src/endtype_controller/__init__.pyi
      - run: mv src/file_controller/__init__.py src/file_controller/__init__.pyi
      - run: mv src/geometry_controller/__init__.py src/geometry_controller/__init__.pyi
      - run: mv src/list_controller/__init__.py src/list_controller/__init__.pyi
      - run: mv src/machine_controller/__init__.py src/machine_controller/__init__.pyi
      - run: mv src/material_controller/__init__.py src/material_controller/__init__.pyi
      - run: mv src/menu_controller/__init__.py src/menu_controller/__init__.pyi
      - run: mv src/roof_controller/__init__.py src/roof_controller/__init__.pyi
      - run: mv src/scene_controller/__init__.py src/scene_controller/__init__.pyi
      - run: mv src/shop_drawing_controller/__init__.py src/shop_drawing_controller/__init__.pyi
      - run: mv src/utility_controller/__init__.py src/utility_controller/__init__.pyi
      - run: mv src/visualization_controller/__init__.py src/visualization_controller/__init__.pyi
      - run: >-
          python -m
          pip install
          build
          --user
      - run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
