name: Publish CwAPI3D Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
